// Constants for fetching a single project
export const FETCH_PROJECT_REQUEST = "FETCH_PROJECT_REQUEST";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILURE = "FETCH_PROJECT_FAILURE";

// Constants for updating a project
export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

// Constants for updating a project's image
export const UPDATE_PROJECT_IMAGE_REQUEST = "UPDATE_PROJECT_IMAGE_REQUEST";
export const UPDATE_PROJECT_IMAGE_SUCCESS = "UPDATE_PROJECT_IMAGE_SUCCESS";
export const UPDATE_PROJECT_IMAGE_FAILURE = "UPDATE_PROJECT_IMAGE_FAILURE";

// Constants for fetching categories
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

// Constants for toggling project like
export const PROJECT_TOGGLE_LIKE_REQUEST = "PROJECT_TOGGLE_LIKE_REQUEST";
export const PROJECT_TOGGLE_LIKE_SUCCESS = "PROJECT_TOGGLE_LIKE_SUCCESS";
export const PROJECT_TOGGLE_LIKE_FAILURE = "PROJECT_TOGGLE_LIKE_FAILURE";
